length=eval(input('enter the length of rectangle'))
breadth=eval(input('enter the length of rectangle'))
print('------------------------------------------')
print("length",length)
print("breadth",breadth)
print('------------------------------------------')
print('area',length*breadth)
print('perimeter',2*(length+breadth))
